// ギリシャ文字
export const greek: { name: string; tex: string }[] = [
  { name: "$\\alpha$", tex: "\\alpha" },
  { name: "$\\beta$", tex: "\\beta" },
  { name: "$\\gamma$", tex: "\\gamma" },
  { name: "$\\delta$", tex: "\\delta" },
  { name: "$\\epsilon$", tex: "\\epsilon" },
  { name: "$\\zeta$", tex: "\\zeta" },
  { name: "$\\eta$", tex: "\\eta" },
  { name: "$\\theta$", tex: "\\theta" },
  { name: "$\\iota$", tex: "\\iota" },
  { name: "$\\kappa$", tex: "\\kappa" },
  { name: "$\\lambda$", tex: "\\lambda" },
  { name: "$\\mu$", tex: "\\mu" },
  { name: "$\\nu$", tex: "\\nu" },
  { name: "$\\xi$", tex: "\\xi" },
  { name: "$o$", tex: "o" },
  { name: "$\\pi$", tex: "\\pi" },
  { name: "$\\rho$", tex: "\\rho" },
  { name: "$\\sigma$", tex: "\\sigma" },
  { name: "$\\tau$", tex: "\\tau" },
  { name: "$\\upsilon$", tex: "\\upsilon" },
  { name: "$\\phi$", tex: "\\phi" },
  { name: "$\\chi$", tex: "\\chi" },
  { name: "$\\psi$", tex: "\\psi" },
  { name: "$\\omega$", tex: "\\omega" },
  { name: "$\\Theta$", tex: "\\Theta" },
  { name: "$\\Xi$", tex: "\\Xi" },
  { name: "$\\Upsilon$", tex: "\\Upsilon" },
  { name: "$\\Gamma$", tex: "\\Gamma" },
  { name: "$\\Phi$", tex: "\\Phi" },
  { name: "$\\Delta$", tex: "\\Delta" },
  { name: "$\\Pi$", tex: "\\Pi" },
  { name: "$\\Lambda$", tex: "\\Lambda" },
  { name: "$\\Psi$", tex: "\\Psi" },
  { name: "$\\Sigma$", tex: "\\Sigma" },
  { name: "$\\Omega$", tex: "\\Omega" },
  { name: "$\\varepsilon$", tex: "\\varepsilon" },
  { name: "$\\vartheta$", tex: "\\vartheta" },
  { name: "$\\varrho$", tex: "\\varrho" },
  { name: "$\\varsigma$", tex: "\\varsigma" },
  { name: "$\\varphi$", tex: "\\varphi" },
];

// 数式
export const mathFormula: { name: string; tex: string }[] = [
  { name: "$\\frac{\\Box}{\\Box}$", tex: "\\frac" },
  { name: "$\\blacksquare^{\\Box}$", tex: "^" },
  { name: "$\\blacksquare_{\\Box}$", tex: "_" },
  { name: "$\\nabla$", tex: "\\nabla" },
  { name: "$\\partial$", tex: "\\partial" },
  { name: "$\\int$", tex: "\\int" },
  { name: "$\\vec{\\Box}$", tex: "\\vec" },
  { name: "$\\overrightarrow{\\Box}$", tex: "\\overrightarrow" },
  { name: "$\\hat{\\Box}$", tex: "\\hat" },
  { name: "$\\infty$", tex: "\\infty" },
  { name: "$\\exp$", tex: "\\exp" },
  { name: "$\\sqrt{\\Box}$", tex: "\\sqrt" },
  { name: "$\\log$", tex: "\\log" },
  { name: "$\\ln$", tex: "\\ln" },
  { name: "$|\\Box|$", tex: "|" },
  { name: "$\\lim$", tex: "\\lim" },
  { name: "$\\sin$", tex: "\\sin" },
  { name: "$\\cos$", tex: "\\cos" },
  { name: "$\\tan$", tex: "\\tan" },
  { name: "$\\arcsin$", tex: "\\arcsin" },
  { name: "$\\arccos$", tex: "\\arccos" },
  { name: "$\\arctan$", tex: "\\arctan" },
  { name: "$\\sinh$", tex: "\\sinh" },
  { name: "$\\cosh$", tex: "\\cosh" },
  { name: "$\\tanh$", tex: "\\tanh" },
  { name: "$\\sum$", tex: "\\sum" },
  { name: "$\\prod$", tex: "\\prod" },
];

// その他
export const otherSymbols = [
  { name: "$=$", tex: "=" },
  { name: "$+$", tex: "+" },
  { name: "$-$", tex: "-" },
  { name: "$\\times$", tex: "\\times" },
  { name: "$\\div$", tex: "\\div" },
  { name: "$\\pm$", tex: "\\pm" },
  { name: "$\\mp$", tex: "\\mp" },
  { name: "$\\neq$", tex: "\\neq" },
  { name: "$\\sim$", tex: "\\sim" },
  { name: "$\\simeq$", tex: "\\simeq" },
  { name: "$\\equiv$", tex: "\\equiv" },
  { name: "$>$", tex: ">" },
  { name: "$<$", tex: "<" },
  { name: "$\\geq$", tex: "\\geq" },
  { name: "$\\leq$", tex: "\\leq" },
  { name: "$\\gg$", tex: "\\gg" },
  { name: "$\\ll$", tex: "\\ll" },
  { name: "$\\cdot$", tex: "\\cdot" },
  { name: "$\\underline{\\Box}$", tex: "\\underline" },
  { name: "$\\overline{\\Box}$", tex: "\\overline" },
  { name: "$\\oplus$", tex: "\\oplus" },
  { name: "$\\ominus$", tex: "\\ominus" },
  { name: "$\\otimes$", tex: "\\otimes" },
  { name: "$\\oslash$", tex: "\\oslash" },
  { name: "$\\circ$", tex: "\\circ" },
  { name: "$\\bullet$", tex: "\\bullet" },
  { name: "$\\cdots$", tex: "\\cdots" },
  { name: "$\\in$", tex: "\\in" },
  { name: "$\\ni$", tex: "\\ni" },
  { name: "$\\notin$", tex: "\\notin" },
  { name: "$\\subset$", tex: "\\subset" },
  { name: "$\\supset$", tex: "\\supset" },
  { name: "$\\subseteq$", tex: "\\subseteq" },
  { name: "$\\supseteq$", tex: "\\supseteq" },
  { name: "$\\cap$", tex: "\\cap" },
  { name: "$\\cup$", tex: "\\cup" },
  { name: "$\\varnothing$", tex: "\\emptyset" },
];
